### ISSUE TITLE
Use Unicode subscripts/superscripts where available?

### ISSUE THREAD

**Issue by stevengj** [bartp5/libtexprintf#20]
Currently `t_0` renders as
```
t
 0
```
However, Unicode has a `0` subscript character, so it could render more cleanly as `t₀`.

In general, if a subscript or superscript consists entirely of characters available as such in Unicode, it would be nice to render them that way (with the current behavior as a fallback for characters lacking Unicode sub/superscripts).

The available Unicode superscripts are `²³¹ʰʲʳʷʸˡˢˣᴬᴮᴰᴱᴳᴴᴵᴶᴷᴸᴹᴺᴼᴾᴿᵀᵁᵂᵃᵇᵈᵉᵍᵏᵐᵒᵖᵗᵘᵛᶜᶠᶻ⁰ⁱ⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁿⱽꜝ` and the subscripts are `ᵢᵣᵤᵥ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎ₐₑₒₓₕₖₗₘₙₚₛₜⱼ`

(In general, there are a lot of Unicode characters that you could potentially be using.   See https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/latex_symbols.jl for a list mapping them from LaTeX and LaTeX-like `\symbols`.)

**Comment by bartp5** [comment]
I like that idea. The fallback will also be needed if a symbol has both sub and superscripts.

**Comment by Suavesito-Olimpiada** [comment]
You could even use subscripts as a superscript and vice versa, something like the next

```tex
\mathbb{R}_0
\sum_{i=0}^{n}{a_i^2}
```

will be rendered as follows

```
ℝ₀ # here 0 is a subscript
n
__
╲   ₍ₙ₋ᵢ₎ # these are subscripts
╱  a
⎺⎺  ᵞᵢ    # this is superscript followed by a subscript
i=0       # but seems like a subscript with its own subscript
```

**Comment by bartp5** [comment]
The difficulty I see is technical. The parser is recursive. When the parser renders a token (part of the input string) into a box, it also creates boxes for the children (e.g. a super-/sub-scripts), and then calls the parser on the sub-/super script to fill the children boxes. The only information the parent gets back is the sizes of the children boxes. This means that the parent knows it has a sub-/super script, however, the sub-/super script itself is  unaware of its status as a sub-/super script. This makes it difficult to handle things like 
`\mathnormal{a_\text{i}}`.
Right now that renders correctly as:
```
𝑎
 i
```
So we want to make that into `𝑎ᵢ`. However, the parent (𝑎) does not know the child (i) uses a text font, and the child does not know it is a subscript. So to know whether I should map the `i` to `ᵢ`, I need to combine information that currently never comes together. This will quickly become ugly and messy... This is not an easy feature to implement.

**Comment by bartp5** [comment]
I pushed a version to the dev branch which implements this (a basic version, no mixing of sub/and superscripts). It correctly does things like:
`src/utftex  -F mathnormal 'a^{\text{n-k}}'` -> `𝑎ⁿ⁻ᵏ`

I also added a switch to turn on or off the mapping (`-m`).

Many equations look better this way but I feel it looks a bit odd if the equations use mixed mapped sub/superscripts and the fallback method, e.g.
```
src/utftex '\left<W_{last\_max}, W_{max}\right>'

╱W        , Wₘₐₓ╲
╲ last_max      ╱
```

You can look at how the test equations now render.

A fairly trivial improvement would be to change the behavior of things like `src/utftex '\sum_{i=0}^N a_i'` to render both "i=0" as well as "N" is super and sub-scripts, respectively. Right now it still does:
```
N
⎯⎯
╲
╱   aᵢ
⎺⎺
i=0
```

**Comment by bartp5** [comment]
@Suavesito-Olimpiada at this point I can only think of rather ugly solutions for your suggestion. So unless I get a better idea I will not work on this. 

Ps. I just realized I should have phantom commands. Then, as an ugly, and very manual workaround, you can do things like:
```
utftex 'a_{\vphantom{a}^y\vphantom{a}_i}'
a
 ʸᵢ
```
That change is easy, so it is now in dev branch.

**Comment by Suavesito-Olimpiada** [comment]
First, thanks for all the work!

I've been thinking on how to do what I proposed, but I still don't have a complete solution. The plan is to save what level of sub/super is the current context (maybe even the stack of calls), and decide based on that if it is necessary to arrange things with sub/super indices or with normal rendering. I'll though about it more and see if I can make a PR.

**Comment by larseggert** [comment]
> Many equations look better this way but I feel it looks a bit odd if the equations use mixed mapped sub/superscripts and the fallback method

Yes, this looks very jarring. Also, depending on the font, different letters of a multi-letter subscript have slightly different baselines and widths, making things look quite bad.
<img width="1005" alt="Screenshot 2023-05-31 at 16 52 41" src="https://github.com/bartp5/libtexprintf/assets/200328/fa526425-ed68-467b-9d4b-91c8be04d474">
(This is with MacOS default Courier.)

**Comment by stevengj** [comment]
Yes, basically you need to use a font with good Unicode coverage.  e.g. https://juliamono.netlify.app/

**Comment by stevengj** [comment]
See also [this stackoverflow answer](https://stackoverflow.com/a/73313342/3662120); I tend to recommend JuliaMono because it was designed specifically for technical computing and so it has good coverage of mathematical symbols in particular.

**Comment by bartp5** [comment]
@stevengj Thanks for the tip. I actually did not know about JuliaMono. I'll test it a bit. I like the sub and superscripts in JuliaMono.

Something that almost never looks good in fonts is the italic "h". At codepoint 1D455 one would expect an italic h but it is left blank. As I understand it, it was left out as the italic h was already defined at 0210E (Planck's constant). However, in most fonts the italic symbols in the 1D45x range are all italic serif, whereas 0210E is usually italic sans. As I map my way around the hole in libtexprintf, I thus usually get an h being out of style with the rest. With JuliaMono I get:
![testJuliaMono](https://github.com/bartp5/libtexprintf/assets/2051341/c5422c6b-cd9d-45cc-8bed-169707eafb80)
So the h is here mostly in style, just a little bit more bold than the rest. Much better than in most fonts.

**Comment by bartp5** [comment]
I merged the changes with the main branch and prepared a new release. I close this issue.
